[package]
name = "penguin"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.5.7"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }

dotenvy = "0.15.7"
rand = "0.8.4"